# Generated by Django 6.0.4 on 2026-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='production_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
