# Generated by Django 6.0.4 on 2026-04-22 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_vehicle_production_year_vehicle_registration_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='production_year',
        ),
    ]
