# Generated by Django 6.0.4 on 2026-04-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_remove_vehicle_production_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_count',
            field=models.IntegerField(default=0),
        ),
    ]
